language: nix
nix: 2.0.4
cache:
  directories:
  - "$HOME/nix.store"
env:
  global:
  - secure: AXFQcthRGqb3yilHNkjKn/X+qRnZk2qT/Le3LTQ+ScerYVGPLbwtuH+kQbsC48wJ2pMUIJ6vwHPv2eOj+nnLRugMw7Rf1VqHRHreaTrJHRV1ErRU3N7el/z5RaYs4wn6n6hmRfu9DeusJTOnNiIxmzKg+78imVP+yWn1JPuapKL27MImPggUEnJQWmfaZRwf5fg2BpbjzMP2QbtZW4a4f490Yk9mbBuqk11Z2LpR3dNQNg6fQAfwE/+P4DmEr1R18CWlkE/8b4n9d9IrbljcPFHa7oKQV36vfoBR87ZF1RC1DlT1deP6i+FyBkZxROVW0CSo4FXnwpkjmYPhBw2ROK+uy++rSFGab1+zJg7G5qOmUYdtDvZPXIw1JyDainmB5/Jecwzb5jAiXFIkcwLMYewURQGeqQj2k1MLeckD3mYnsgL8ehWaFbTNUUhDwbjkr+CXwXIvWyZk+JvwquVVQ4rVR2APLqgfb9+WhAXXR0ofRs+tLUk7fGLwwpJQV7O/eo/DtoF9jGsliAja144nSTnvsAYV2xhQ4Z1z4D81EJ/ndf1+Jbe/TZqKa9h7eriOLkBHBgJgGrWZapQ/FyrBu/fQgK0/Gmt0vbyHZxrUlGHohLeZtX+M+tQhbdk45QPcvA5wOdhfnuNYtOjXmCVuRZoU1l1OQ3fJJ02RzIXST9o=

before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee
  -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
before_script:
- nix-env -iA cachix -f https://cachix.org/api/v1/install
- cachix use ergvein
script:
- nix-build -A ghc.ergvein-wallet | cachix push ergvein
- nix-build -A ghc.ergvein-index-server | cachix push ergvein
- nix-build --arg isAndroid true -A android.ergvein-wallet | cachix push ergvein
