serverPort               : 8085
serverTcpPort            : 8667
dbPath                   : "./ergveinDb"
BTCNodeIsTestnet         : true
BTCNodeHost              : localhost
BTCNodePort              : 18332
BTCNodeUser              : bitcoinrpc
BTCNodePassword          : password
ERGONodeHost             : localhost
ERGONodePort             : 9052
blockchainScanDelay      : 1000000
ownPeerAddress           : null
knownPeers               :
                           - "120.0.0.1:8882"
                           - "120.0.0.1:8883"
peerActualizationDelay   : 10000000
peerActualizationTimeout : 86400