serverPort               : 8085
serverTcpPort            : 18667
dbPath                   : "./db"
BTCNodeIsTestnet         : true
BTCNodeHost              : localhost
BTCNodePort              : 18332
BTCNodeUser              : bitcoinrpc
BTCNodePassword          : password
BTCNodeTCPHost           : localhost
BTCNodeTCPPort           : 18333
ERGONodeHost             : localhost
ERGONodePort             : 9052
blockchainScanDelay      : 10000000
ownPeerAddress           : null
knownPeers               : []
peerActualizationDelay   : 10000000
peerActualizationTimeout : 86400
ratesRefreshPeriod       : 300000000          # 5 minutes
metrics:
  host: localhost
  port: 9667
