serverPort               : 8085
serverTcpPort            : 8667
filtersDbPath            : "./db/mainnet_filters.db"
indexerDbPath            : "./db/mainnet_indexer.db"
utxoDbPath               : "./db/mainnet_utxo.db"
BTCNodeIsTestnet         : false
BTCNodeHost              : localhost
BTCNodePort              : 8332
BTCNodeUser              : bitcoin
BTCNodePassword          : AeNungaengohpeeG4eX5
BTCNodeTCPHost           : localhost
BTCNodeTCPPort           : 8333
ERGONodeHost             : localhost
ERGONodePort             : 9052
blockchainScanDelay      : 10000000
ownPeerAddress           : null
knownPeers               : []
peerActualizationDelay   : 10000000
peerActualizationTimeout : 86400
ratesRefreshPeriod       : 300000000          # 5 minutes
metrics:
  host: localhost
  port: 9667
