name: Build all
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-desktop:
    name: Build desktop platform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - name: Setup cachix
      uses: cachix/cachix-action@v8
      with:
        name: ergvein
        signingKey: ${{ secrets.CACHIX_KEY }}

    - name: Extract git commit hash
      shell: bash
      run: echo "##[set-output name=githash;]$(git rev-parse --short HEAD)"
      id: extract_githash

    - name: Build indexer server
      env:
        GIT_HASH: ${{ steps.extract_githash.outputs.githash }}
      run: nix-build -A ghc.ergvein-index-server --arg gitHash "\"$GIT_HASH\""

    - name: Build desktop wallet
      env:
        GIT_HASH: ${{ steps.extract_githash.outputs.githash }}
      run: |
        nix-build -A ghc.ergvein-wallet --arg gitHash "\"$GIT_HASH\""

  build-android:
    name: Build android platform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - name: Setup cachix
      uses: cachix/cachix-action@v8
      with:
        name: ergvein
        signingKey: ${{ secrets.CACHIX_KEY }}

    - name: Extract git commit hash
      shell: bash
      run: echo "##[set-output name=githash;]$(git rev-parse --short HEAD)"
      id: extract_githash

    - name: Build android wallet
      env:
        GIT_HASH: ${{ steps.extract_githash.outputs.githash }}
      run: |
        nix-build --arg isAndroid true --arg gitHash "\"$GIT_HASH\"" -A android.ergvein-wallet -o android-result
